# Generated by Django 4.2.2 on 2023-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_userprofile_delete_storeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenre',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
