# Generated by Django 4.2.2 on 2023-06-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_userratedbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userratedbooks',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
